export const LOBE_THEME_APPEARANCE = 'PUERHUB_THEME_APPEARANCE';

export const LOBE_THEME_PRIMARY_COLOR = 'PUERHUB_THEME_PRIMARY_COLOR';

export const LOBE_THEME_NEUTRAL_COLOR = 'PUERHUB_THEME_NEUTRAL_COLOR';
